/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HelloWorld;

import java.util.HashMap;

public class Library {
	public static void main(String[] args) {
		String name = "This is a name";
		
		
		Song thisSong = new Song("Catch the Wave",180,"kz");
		
		System.out.println(name);
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
